// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using RegulatorIQ.Data;

#nullable disable

namespace RegulatorIQ.API.Migrations
{
    [DbContext(typeof(RegulatorIQContext))]
    partial class RegulatorIQContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "uuid-ossp");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("RegulatorIQ.Models.ChangeImpactAssessment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AffectedProcesses")
                        .HasColumnType("jsonb");

                    b.Property<string>("AssessedBy")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<DateTime>("AssessmentDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("DocumentId")
                        .HasColumnType("uuid");

                    b.Property<decimal?>("EstimatedCost")
                        .HasColumnType("decimal(15,2)");

                    b.Property<Guid?>("FrameworkId")
                        .HasColumnType("uuid");

                    b.Property<decimal?>("ImpactScore")
                        .HasColumnType("decimal(5,2)");

                    b.Property<int?>("ImplementationComplexity")
                        .HasColumnType("integer");

                    b.Property<string>("RequiredUpdates")
                        .HasColumnType("jsonb");

                    b.Property<string>("RiskLevel")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("TimelineConflicts")
                        .HasColumnType("jsonb");

                    b.HasKey("Id");

                    b.HasIndex("DocumentId");

                    b.HasIndex("FrameworkId");

                    b.ToTable("ChangeImpactAssessments");
                });

            modelBuilder.Entity("RegulatorIQ.Models.ComplianceFramework", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("FrameworkData")
                        .HasColumnType("jsonb");

                    b.Property<string>("FrameworkName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("FrameworkVersion")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string[]>("GeographicScope")
                        .HasColumnType("text[]");

                    b.Property<string[]>("IndustrySegments")
                        .HasColumnType("text[]");

                    b.Property<DateTime>("LastUpdated")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId")
                        .HasDatabaseName("idx_frameworks_company");

                    b.ToTable("ComplianceFrameworks");
                });

            modelBuilder.Entity("RegulatorIQ.Models.ComplianceRequirement", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string[]>("Applicability")
                        .HasColumnType("text[]");

                    b.Property<string>("Citation")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int?>("ComplexityLevel")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("Deadline")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("DocumentId")
                        .HasColumnType("uuid");

                    b.Property<decimal?>("EstimatedCostImpact")
                        .HasColumnType("decimal(15,2)");

                    b.Property<string>("ImplementationGuidance")
                        .HasColumnType("text");

                    b.Property<string>("RequirementText")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("RequirementType")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Severity")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("Id");

                    b.HasIndex("Deadline")
                        .HasDatabaseName("idx_requirements_deadline")
                        .HasFilter("deadline IS NOT NULL");

                    b.HasIndex("DocumentId");

                    b.ToTable("ComplianceRequirements");
                });

            modelBuilder.Entity("RegulatorIQ.Models.DocumentAnalysis", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ActionableItems")
                        .HasColumnType("jsonb");

                    b.Property<string[]>("AffectedParties")
                        .HasColumnType("text[]");

                    b.Property<DateTime>("AnalysisDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("AnalysisVersion")
                        .HasColumnType("integer");

                    b.Property<string>("AnalyzerVersion")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Classification")
                        .HasColumnType("jsonb");

                    b.Property<string>("ComplianceRequirements")
                        .HasColumnType("jsonb");

                    b.Property<decimal>("ConfidenceScore")
                        .HasColumnType("decimal(3,2)");

                    b.Property<Guid>("DocumentId")
                        .HasColumnType("uuid");

                    b.Property<string>("EntitiesExtracted")
                        .HasColumnType("jsonb");

                    b.Property<string>("ImpactAssessment")
                        .HasColumnType("jsonb");

                    b.Property<string[]>("RelatedRegulations")
                        .HasColumnType("text[]");

                    b.Property<string>("Summary")
                        .HasColumnType("text");

                    b.Property<string>("TimelineAnalysis")
                        .HasColumnType("jsonb");

                    b.HasKey("Id");

                    b.HasIndex("DocumentId");

                    b.ToTable("DocumentAnalyses");
                });

            modelBuilder.Entity("RegulatorIQ.Models.FrameworkRegulationMapping", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AssignedTo")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("ComplianceStatus")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("DocumentId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("DueDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("FrameworkId")
                        .HasColumnType("uuid");

                    b.Property<string>("ImplementationStatus")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("MappingType")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Notes")
                        .HasColumnType("text");

                    b.Property<Guid?>("RequirementId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("DocumentId");

                    b.HasIndex("FrameworkId");

                    b.HasIndex("RequirementId");

                    b.ToTable("FrameworkRegulationMappings");
                });

            modelBuilder.Entity("RegulatorIQ.Models.RegulatoryAgency", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Abbreviation")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<string>("AgencyType")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("ApiEndpoint")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("ContactInfo")
                        .HasColumnType("jsonb");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Jurisdiction")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<bool>("MonitoringEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("WebsiteUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.HasKey("Id");

                    b.ToTable("RegulatoryAgencies");
                });

            modelBuilder.Entity("RegulatorIQ.Models.RegulatoryAlert", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("AcknowledgedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("AcknowledgedBy")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("AlertData")
                        .HasColumnType("jsonb");

                    b.Property<string>("AlertType")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("DocumentId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("FrameworkId")
                        .HasColumnType("uuid");

                    b.Property<string>("Message")
                        .HasColumnType("text");

                    b.Property<string>("Severity")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Title")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.HasKey("Id");

                    b.HasIndex("DocumentId");

                    b.HasIndex("FrameworkId");

                    b.HasIndex("Status", "CreatedAt")
                        .HasDatabaseName("idx_alerts_status_created");

                    b.ToTable("RegulatoryAlerts");
                });

            modelBuilder.Entity("RegulatorIQ.Models.RegulatoryAuditLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("ChangeReason")
                        .HasColumnType("text");

                    b.Property<string>("ChangedBy")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("EntityId")
                        .HasColumnType("uuid");

                    b.Property<string>("EntityType")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("NewData")
                        .HasColumnType("jsonb");

                    b.Property<string>("OldData")
                        .HasColumnType("jsonb");

                    b.HasKey("Id");

                    b.ToTable("RegulatoryAuditLogs");
                });

            modelBuilder.Entity("RegulatorIQ.Models.RegulatoryDocument", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("AgencyId")
                        .HasColumnType("uuid");

                    b.Property<string>("CfrCitation")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime?>("CommentDeadline")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("ComplianceDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DocketNumber")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("DocumentId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("DocumentType")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime?>("EffectiveDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("FederalRegisterNumber")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("PdfUrl")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<int>("PriorityScore")
                        .HasColumnType("integer");

                    b.Property<string>("ProcessedContent")
                        .HasColumnType("text");

                    b.Property<DateTime?>("PublicationDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("RawContent")
                        .HasColumnType("text");

                    b.Property<string>("SourceUrl")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("EffectiveDate")
                        .HasDatabaseName("idx_documents_effective_date")
                        .HasFilter("effective_date IS NOT NULL");

                    b.HasIndex("PriorityScore")
                        .HasDatabaseName("idx_documents_priority");

                    b.HasIndex("AgencyId", "PublicationDate")
                        .HasDatabaseName("idx_documents_agency_date");

                    b.ToTable("RegulatoryDocuments");
                });

            modelBuilder.Entity("RegulatorIQ.Models.ChangeImpactAssessment", b =>
                {
                    b.HasOne("RegulatorIQ.Models.RegulatoryDocument", "Document")
                        .WithMany("ImpactAssessments")
                        .HasForeignKey("DocumentId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("RegulatorIQ.Models.ComplianceFramework", "Framework")
                        .WithMany("ImpactAssessments")
                        .HasForeignKey("FrameworkId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Document");

                    b.Navigation("Framework");
                });

            modelBuilder.Entity("RegulatorIQ.Models.ComplianceRequirement", b =>
                {
                    b.HasOne("RegulatorIQ.Models.RegulatoryDocument", "Document")
                        .WithMany("ComplianceRequirements")
                        .HasForeignKey("DocumentId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Document");
                });

            modelBuilder.Entity("RegulatorIQ.Models.DocumentAnalysis", b =>
                {
                    b.HasOne("RegulatorIQ.Models.RegulatoryDocument", "Document")
                        .WithMany("Analyses")
                        .HasForeignKey("DocumentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Document");
                });

            modelBuilder.Entity("RegulatorIQ.Models.FrameworkRegulationMapping", b =>
                {
                    b.HasOne("RegulatorIQ.Models.RegulatoryDocument", "Document")
                        .WithMany()
                        .HasForeignKey("DocumentId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("RegulatorIQ.Models.ComplianceFramework", "Framework")
                        .WithMany("RegulationMappings")
                        .HasForeignKey("FrameworkId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("RegulatorIQ.Models.ComplianceRequirement", "Requirement")
                        .WithMany()
                        .HasForeignKey("RequirementId");

                    b.Navigation("Document");

                    b.Navigation("Framework");

                    b.Navigation("Requirement");
                });

            modelBuilder.Entity("RegulatorIQ.Models.RegulatoryAlert", b =>
                {
                    b.HasOne("RegulatorIQ.Models.RegulatoryDocument", "Document")
                        .WithMany()
                        .HasForeignKey("DocumentId");

                    b.HasOne("RegulatorIQ.Models.ComplianceFramework", "Framework")
                        .WithMany()
                        .HasForeignKey("FrameworkId");

                    b.Navigation("Document");

                    b.Navigation("Framework");
                });

            modelBuilder.Entity("RegulatorIQ.Models.RegulatoryDocument", b =>
                {
                    b.HasOne("RegulatorIQ.Models.RegulatoryAgency", "Agency")
                        .WithMany()
                        .HasForeignKey("AgencyId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Agency");
                });

            modelBuilder.Entity("RegulatorIQ.Models.ComplianceFramework", b =>
                {
                    b.Navigation("ImpactAssessments");

                    b.Navigation("RegulationMappings");
                });

            modelBuilder.Entity("RegulatorIQ.Models.RegulatoryDocument", b =>
                {
                    b.Navigation("Analyses");

                    b.Navigation("ComplianceRequirements");

                    b.Navigation("ImpactAssessments");
                });
#pragma warning restore 612, 618
        }
    }
}
